Add pytest result to github actions.

diff --git a/.github/workflows/pytest_workflow.yml b/.github/workflows/pytest_workflow.yml
--- a/.github/workflows/pytest_workflow.yml
+++ b/.github/workflows/pytest_workflow.yml
@@ -32,3 +32,11 @@ jobs:
       - name: Check Coverage
         run: |
           coverage report -m --fail-under=70
+
+      - name: Check Pytest Pass
+        run: |
+          pytest_status=$?
+          if [ $pytest_status -ne 0 ]; then
+            echo "Pytest failed. Check the test logs for more details."
+            exit 1
+          fi
